# Generated by Django 5.0.6 on 2024-05-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='name',
            field=models.CharField(blank=True, default='Income', max_length=30, null=True),
        ),
    ]
